name: Update README with RSS feed

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y jq xmllint

      - name: Extract RSS feed and update README
        run: |
          curl -s https://blog.abhishekkandel.com.np/rss.xml -o feed.xml
          xmllint --format feed.xml | \
          grep -o '<link>[^<]*</link>' | \
          sed 's/<link>\(.*\)<\/link>/\1/' | \
          head -n 5 > latest-blogs.txt
          blogs=$(awk '{print "- [" $0 "](" $0 ")"}' latest-blogs.txt)
          sed -i '/<!-- latest-posts-start -->/,/<!-- latest-posts-end -->/{//!d}' README.md
          sed -i "/<!-- latest-posts-start -->/a $blogs" README.md
          rm feed.xml latest-blogs.txt

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with latest blog posts'
          git push