name: Update README with RSS feed

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          git clone https://github.com/${{ github.repository }}.git repo
          cd repo

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq libxml2-utils

      - name: Extract RSS feed and update README
        run: |
          cd repo
          curl -s https://blog.abhishekkandel.com.np/rss.xml -o feed.xml
          echo "Downloaded RSS feed:"
          cat feed.xml

          xmllint --format feed.xml | grep -o '<link>[^<]*</link>' | sed 's/<link>\(.*\)<\/link>/\1/' | head -n 5 > latest-blogs.txt
          echo "Extracted links:"
          cat latest-blogs.txt

          blogs=$(awk '{print "- [" $0 "](" $0 ")"}' latest-blogs.txt | tr '\n' ' ')
          echo "Formatted blog links:"
          echo "$blogs"

          sed -i '/<!-- latest-posts-start -->/,/<!-- latest-posts-end -->/{//!d}' README.md
          sed -i "/<!-- latest-posts-start -->/a $blogs" README.md
          echo "Updated README.md content:"
          cat README.md

          rm feed.xml latest-blogs.txt

      - name: Commit changes
        run: |
          cd repo
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with latest blog posts'
          git push